apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-sidecar
data:
  container_name: count
  grep_pattern: 'Y\w+\s+F\w+$'
  sleep_time: '60'
  log_server_uri: 'http://localhost/datafeed'
  feed_name_header: CSV_FEED
  system_name_header: EXAMPLE_SYSTEM
  env_name_header: EXAMPLE_ENVIRONMENT
  dedupe: 'true'
